baseURL = 'https://kitintale.sirapollokaggwaschools.co.ug/'
locale = 'en-us'
title = 'Sir Apollo Kaggwa Primary School - kitintale'
theme = "saks-theme"

[params]
logo = "/img/logo.png"
mainSchool = false
